export const articleMetadata = [
  {
    slug: "/resources/do-ats-systems-reject-75-percent",
    title: "Do ATS Systems Really Reject 75% of CVs?",
    track: "candidate",
    stage: "understand",
    readingGoal: "understand",
    order: 1,
    journeyMode: "forward",
    label: "The shift that actually matters",
    nextArticle: {
      slug: "/resources/how-ai-screening-actually-works",
      title: "How AI Screening Actually Works",
      copy: "The 75% ATS rejection story is still misleading. But while everyone was busy keyword-stuffing to beat a filing cabinet, the more significant change was happening elsewhere: AI-assisted ranking and recommendation systems quietly becoming part of how applications get sorted. That is a separate conversation, and a more relevant one.",
    },
    relatedArticles: [],
    cta: "interview-coach",
    readTime: "9 min read",
    excerpt: "The 75% figure is everywhere. The problem is that it is not true, and the myth has sent candidates chasing the wrong problem.",
  },
  {
    slug: "/resources/how-ai-screening-actually-works",
    title: "How AI Screening Actually Works",
    track: "candidate",
    stage: "understand",
    readingGoal: "understand",
    order: 2,
    journeyMode: "forward",
    label: "Next in the journey",
    nextArticle: {
      slug: "/resources/can-you-tell-when-ai-is-screening-your-application",
      title: "Can You Tell When AI Is Screening Your Application?",
      copy: "The irony is that many candidates spend hours trying to optimise for AI systems they may never encounter, while completely missing the ones they already have. If these tools are increasingly deciding who gets seen, the obvious question is whether you can even tell when they are being used on you.",
    },
    relatedArticles: [],
    cta: "interview-coach",
    readTime: "8 min read",
    excerpt: "AI shapes the shortlist. People still make the offer. This is what the tools actually do and where their limits sit.",
  },
  {
    slug: "/resources/can-you-tell-when-ai-is-screening-your-application",
    title: "Can You Tell When AI Is Screening Your Application?",
    track: "candidate",
    stage: "understand",
    readingGoal: "understand",
    order: 3,
    journeyMode: "forward",
    label: "Moving into: Adapt Your Approach",
    nextArticle: {
      slug: "/resources/the-cv-didnt-change",
      title: "The CV Didn't Change. The Reading Did.",
      copy: "Understanding the system is only half the challenge. The next step is adapting to it. Starting with the document most affected by everything covered here: your CV.",
    },
    relatedArticles: [],
    cta: "interview-coach",
    readTime: "8 min read",
    excerpt: "In many cases you will not be told clearly. Here are the signals to look for, your rights, and what you can do.",
  },
  {
    slug: "/resources/the-cv-didnt-change",
    title: "The CV Didn't Change. The Reading Did.",
    track: "candidate",
    stage: "adapt",
    readingGoal: "adapt",
    order: 4,
    journeyMode: "forward",
    label: "Next in the journey",
    nextArticle: {
      slug: "/resources/ats-friendly-cvs-what-matters",
      title: "ATS-Friendly CVs: What Actually Matters",
      copy: "If your CV now has a machine reader as well as a human one, the practical question is how you format and structure it so the machine reads it accurately. That is the mechanics, and it is the next article.",
    },
    relatedArticles: [],
    cta: "interview-coach",
    readTime: "9 min read",
    excerpt: "Your CV now has two readers. Most people write for one.",
  },
  {
    slug: "/resources/ats-friendly-cvs-what-matters",
    title: "ATS-Friendly CVs: What Actually Matters",
    track: "candidate",
    stage: "adapt",
    readingGoal: "adapt",
    order: 5,
    journeyMode: "forward",
    label: "Next in the journey",
    nextArticle: {
      slug: "/resources/applications-you-never-hear-back-from",
      title: "The Applications You Never Hear Back From",
      copy: "You now have a CV that reads cleanly for both readers. But here is the uncomfortable truth: even a perfect CV is often not enough on its own. The next article is about why so many strong applications simply vanish, and what to do about it.",
    },
    relatedArticles: [],
    cta: "interview-coach",
    readTime: "7 min read",
    excerpt: "Stop optimising for myths. This is what actually helps an ATS and a human read your CV accurately.",
  },
  {
    slug: "/resources/applications-you-never-hear-back-from",
    title: "The Applications You Never Hear Back From",
    track: "candidate",
    stage: "adapt",
    readingGoal: "adapt",
    order: 6,
    journeyMode: "forward",
    label: "Moving into: Perform",
    nextArticle: {
      slug: "/resources/four-types-of-interview-question",
      title: "The 4 Types of Interview Question",
      copy: "Everything so far has been about getting seen. The next stage is about what happens once you are in the room. The interview is still where hiring decisions are actually made, and it is still entirely human.",
    },
    relatedArticles: [],
    cta: "interview-coach",
    readTime: "7 min read",
    excerpt: "You can be qualified and invisible at the same time. This is why strong applications vanish, and what to do about it.",
  },
  {
    slug: "/resources/four-types-of-interview-question",
    title: "The 4 Types of Interview Question",
    track: "candidate",
    stage: "perform",
    readingGoal: "perform",
    order: 7,
    journeyMode: "forward",
    label: "Next in the journey",
    nextArticle: {
      slug: "/resources/star-method",
      title: "The STAR Method",
      copy: "Knowing which type of question you are facing is the first move. The second is knowing how to structure your answer. The STAR method is the most reliable framework for the type of question that matters most - and most people use it wrong.",
    },
    relatedArticles: [],
    cta: "interview-coach",
    readTime: "6 min read",
    excerpt: "Most interview questions fall into four categories. Once you know the type, you know how to structure the answer.",
  },
  {
    slug: "/resources/star-method",
    title: "The STAR Method",
    track: "candidate",
    stage: "perform",
    readingGoal: "perform",
    order: 8,
    journeyMode: "forward",
    label: "Next in the journey",
    nextArticle: {
      slug: "/resources/weakness-question",
      title: "The Weakness Question",
      copy: "STAR gives you the structure. The weakness question is where that structure gets tested hardest - because it is the one question candidates most reliably overthink, and most reliably get wrong.",
    },
    relatedArticles: [],
    cta: "interview-coach",
    readTime: "7 min read",
    excerpt: "Situation, Task, Action, Result is reliable, but most people use it wrong. Here is what good actually looks like.",
  },
  {
    slug: "/resources/weakness-question",
    title: "The Weakness Question",
    track: "candidate",
    stage: "perform",
    readingGoal: "perform",
    order: 9,
    journeyMode: "forward",
    label: "Next in the journey",
    nextArticle: {
      slug: "/resources/specificity-principle",
      title: "The Specificity Principle",
      copy: "Once you have a genuine answer, the next question is what separates a good answer from a memorable one. The difference almost always comes down to one thing: specificity. Vague answers lose. Specific ones land.",
    },
    relatedArticles: [],
    cta: "interview-coach",
    readTime: "5 min read",
    excerpt: "\"I'm a perfectionist\" tells interviewers nothing useful. This is what a strong, honest answer needs instead.",
  },
  {
    slug: "/resources/specificity-principle",
    title: "The Specificity Principle",
    track: "candidate",
    stage: "perform",
    readingGoal: "perform",
    order: 10,
    journeyMode: "forward",
    label: "Next in the journey",
    nextArticle: {
      slug: "/resources/ai-interview-prep",
      title: "Using AI to Prepare Without Sounding Like a Robot",
      copy: "Specifics make an answer land. The next question is how to use AI to sharpen those specifics without letting it write them for you.",
    },
    relatedArticles: [],
    cta: "interview-coach",
    readTime: "6 min read",
    excerpt: "Vague answers lose. Specific answers land. This is how to turn claims into evidence.",
  },
  {
    slug: "/resources/ai-interview-prep",
    title: "Using AI to Prepare Without Sounding Like a Robot",
    track: "candidate",
    stage: "perform",
    readingGoal: "perform",
    order: 11,
    journeyMode: "forward",
    label: "Ready to practise?",
    nextArticle: {
      slug: "https://coach.aievolvingyou.com",
      title: "Interview Coach",
      copy: "You have the frameworks. You have the prep. The last step is putting it under pressure. The Interview Coach gives you a live session with questions matched to your role, real-time feedback, and a personalised cheat sheet.",
      action: "Try for free",
    },
    relatedArticles: [],
    cta: null,
    readTime: "6 min read",
    excerpt: "Generate questions, not answers. Use AI to sharpen your thinking without letting it flatten your voice.",
  },
  {
    slug: "/resources/weakness-question-examples",
    title: "Weakness Question Examples",
    track: "candidate",
    stage: "quick-answer",
    readingGoal: "perform",
    order: null,
    journeyMode: "related",
    label: "Related Reading",
    nextArticle: null,
    relatedArticles: [
      { slug: "/resources/weakness-question", title: "The Weakness Question" },
      { slug: "/resources/star-method", title: "The STAR Method" },
    ],
    cta: "interview-coach",
    readTime: "7 min read",
    excerpt: "Built weakness answers to adapt, after you understand the strategy.",
  },
  {
    slug: "/resources/career-changers",
    title: "Interview Tips for Career Changers",
    track: "candidate",
    stage: "quick-answer",
    readingGoal: "adapt",
    order: null,
    journeyMode: "related",
    label: "Related Reading",
    nextArticle: null,
    relatedArticles: [
      { slug: "/resources/the-cv-didnt-change", title: "The CV Didn't Change. The Reading Did." },
      { slug: "/resources/applications-you-never-hear-back-from", title: "The Applications You Never Hear Back From" },
    ],
    cta: "interview-coach",
    readTime: "6 min read",
    excerpt: "How to frame a non-linear career so the logic is visible to employers.",
  },
  {
    slug: "/resources/interviewing-after-long-gap",
    title: "Interviewing After a Long Gap",
    track: "candidate",
    stage: "quick-answer",
    readingGoal: "perform",
    order: null,
    journeyMode: "related",
    label: "Related Reading",
    nextArticle: null,
    relatedArticles: [
      { slug: "/resources/the-cv-didnt-change", title: "The CV Didn't Change. The Reading Did." },
      { slug: "/resources/specificity-principle", title: "The Specificity Principle" },
    ],
    cta: "interview-coach",
    readTime: "6 min read",
    excerpt: "How to talk about a gap clearly, calmly, and without apologising for it.",
  },
  {
    slug: "/resources/ai-hiring-trust-problem",
    title: "AI in hiring has created a trust problem on both sides of the table",
    track: "org",
    stage: "understand-risk",
    readingGoal: "understand",
    order: null,
    journeyMode: null,
    label: null,
    nextArticle: null,
    relatedArticles: [],
    cta: "toolkit-2",
    readTime: "8 min read",
    excerpt: "Candidates do not trust the process. Organisations do not trust the applications. AI is intensifying both problems.",
  },
  {
    slug: "/resources/ai-procurement-mistakes",
    title: "What most organisations get wrong when buying AI hiring tools",
    track: "org",
    stage: "create-governance",
    readingGoal: "adapt",
    order: null,
    journeyMode: null,
    label: null,
    nextArticle: null,
    relatedArticles: [],
    cta: "toolkit-1",
    readTime: "9 min read",
    excerpt: "Most procurement conversations start too late, ask the wrong questions, and protect the vendor more than the buyer.",
  },
  {
    slug: "/resources/ai-hiring-bias",
    title: "AI did not remove bias from hiring. It gave it a uniform and a spreadsheet.",
    track: "org",
    stage: "build-trust-fairness",
    readingGoal: "understand",
    order: null,
    journeyMode: null,
    label: null,
    nextArticle: null,
    relatedArticles: [],
    cta: "toolkit-3",
    readTime: "9 min read",
    excerpt: "The fairness case for AI hiring looked simple. The evidence now tells a more difficult story.",
  },
  {
    slug: "/resources/ai-hiring-ownership",
    title: "Who owns AI in your hiring process?",
    track: "org",
    stage: "create-governance",
    readingGoal: "adapt",
    order: null,
    journeyMode: null,
    label: null,
    nextArticle: null,
    relatedArticles: [],
    cta: "toolkit-4",
    readTime: "9 min read",
    excerpt: "When something goes wrong with an AI hiring tool, accountability tends to dissolve. Governance has to name the owner.",
  },
  {
    slug: "/resources/how-many-ai-tools-in-hiring",
    title: "How many AI tools are already in your hiring process?",
    track: "org",
    stage: "understand-risk",
    readingGoal: "understand",
    order: null,
    journeyMode: null,
    label: null,
    nextArticle: null,
    relatedArticles: [],
    cta: "toolkit-4",
    readTime: "8 min read",
    excerpt: "Most teams underestimate how many AI features already touch hiring. Governance starts with counting them.",
  },
  {
    slug: "/resources/what-to-tell-candidates-about-ai",
    title: "What should candidates be told about AI?",
    track: "org",
    stage: "build-trust-fairness",
    readingGoal: "adapt",
    order: null,
    journeyMode: null,
    label: null,
    nextArticle: null,
    relatedArticles: [],
    cta: "toolkit-2",
    readTime: "7 min read",
    excerpt: "Transparency is not about explaining the algorithm. It is about telling candidates what AI affects and what stays human.",
  },
];

export const articleMetadataBySlug = Object.fromEntries(articleMetadata.map((article) => [article.slug, article]));

const coreStages = new Set(["understand", "adapt", "perform"]);

export function validateArticleMetadata(metadata = articleMetadata) {
  const slugs = new Set(metadata.map((article) => article.slug));
  const ordersByStage = new Map();

  for (const article of metadata) {
    const required = ["slug", "title", "track", "stage", "readingGoal", "journeyMode", "relatedArticles"];
    for (const field of required) {
      if (!(field in article)) {
        throw new Error(`Article metadata missing ${field}: ${article.slug || article.title || "unknown article"}`);
      }
    }

    if (article.track === "candidate" && coreStages.has(article.stage)) {
      if (article.order == null) {
        throw new Error(`Core journey article has null order: ${article.slug}`);
      }

      const key = `${article.stage}:${article.order}`;
      const existing = ordersByStage.get(key);
      if (existing) {
        throw new Error(`Order collision in ${article.stage} order ${article.order}: ${existing} and ${article.slug}`);
      }
      ordersByStage.set(key, article.slug);

      if (article.journeyMode !== "forward" || !article.nextArticle?.slug) {
        throw new Error(`Core journey article missing nextArticle: ${article.slug}`);
      }
    }

    if (article.journeyMode === "forward" && article.nextArticle?.slug && !article.nextArticle.slug.startsWith("http") && !slugs.has(article.nextArticle.slug)) {
      throw new Error(`Broken nextArticle slug on ${article.slug}: ${article.nextArticle.slug}`);
    }
  }
}

validateArticleMetadata();
